language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - hihyun16@gmail.com
