version: "3.8"

services:
  mysql:
    container_name: mariadb
    image: mariadb:11.0.3
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=operation-together
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
